/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Contont: typeof import('./src/components/tw-music/components/contont.vue')['default']
    Cover: typeof import('./src/components/tw-music/components/cover.vue')['default']
    List: typeof import('./src/components/tw-music/components/list.vue')['default']
    TwMusic: typeof import('./src/components/tw-music/index.vue')['default']
  }
}
